Fix building for FreeBSD
On FreeBSD, _assert() is a macro in <assert.h>.  The macro expansion
causes build errors like this:

	/build/source/src/LercLib/fpl_Lerc2Ext.cpp:34:6: error: expected unqualified-id
	   34 | void _assert(bool v)
	      |      ^
	/nix/store/zgvh12biq5svwz3m0s6dbcvkyrm2fbz4-libc-x86_64-unknown-freebsd-14.1.0/include/assert.h:51:22: note: expanded from macro '_assert'
	   51 | #define _assert(e)      ((void)0)
	      |                           ^
	/build/source/src/LercLib/fpl_Lerc2Ext.cpp:34:6: error: expected ')'
	/nix/store/zgvh12biq5svwz3m0s6dbcvkyrm2fbz4-libc-x86_64-unknown-freebsd-14.1.0/include/assert.h:51:22: note: expanded from macro '_assert'
	   51 | #define _assert(e)      ((void)0)
	      |                           ^
	/build/source/src/LercLib/fpl_Lerc2Ext.cpp:34:6: note: to match this '('
	/nix/store/zgvh12biq5svwz3m0s6dbcvkyrm2fbz4-libc-x86_64-unknown-freebsd-14.1.0/include/assert.h:51:21: note: expanded from macro '_assert'
	   51 | #define _assert(e)      ((void)0)
	      |                          ^
	/build/source/src/LercLib/fpl_Lerc2Ext.cpp:34:6: error: expected ')'
	   34 | void _assert(bool v)
	      |      ^
	/nix/store/zgvh12biq5svwz3m0s6dbcvkyrm2fbz4-libc-x86_64-unknown-freebsd-14.1.0/include/assert.h:51:27: note: expanded from macro '_assert'
	   51 | #define _assert(e)      ((void)0)
	      |                                ^
	/build/source/src/LercLib/fpl_Lerc2Ext.cpp:34:6: note: to match this '('
	/nix/store/zgvh12biq5svwz3m0s6dbcvkyrm2fbz4-libc-x86_64-unknown-freebsd-14.1.0/include/assert.h:51:20: note: expanded from macro '_assert'
	   51 | #define _assert(e)      ((void)0)
	      |                         ^